name: TLFeed Bot

on:
  schedule:
    - cron: "0,30 * * * *"  # every half and full hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # important
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Run TL Notice script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python tlnotice.py

      - name: Commit updated ids.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ids.json
          git commit -m "Update article IDs [skip ci]" || echo "No changes to commit"
          git push